CREATE UNIQUE INDEX IDKHOAHOC_INDEX
ON dbo.KHOAHOC (IDKHOAHOC)
GO
CREATE INDEX IDNGUOIDUNG_INDEX
ON dbo.NGUOIDUNG (USERNAME)
GO
CREATE INDEX IDGIAOVIEN_INDEX
ON dbo.GIAOVIEN (USERNAMEGV)
GO
CREATE UNIQUE INDEX IDVI_INDEX
ON dbo.VIDIENTU (IDVI)
GO
CREATE INDEX IDVI_IDGIAODICH_INDEX
ON dbo.GIAODICH (IDGIAODICH, IDVI)
GO
CREATE UNIQUE INDEX THUOCCHUDE_INDEX
ON dbo.THUOCCHUDE (IDKHOAHOC)
GO
CREATE INDEX KHOAHOC_HOCPHI_INDEX
ON dbo.KHOAHOC (IDKHOAHOC,HOCPHI)
GO
CREATE UNIQUE INDEX IDHOCPHAN
ON dbo.HOCPHAN (IDHOCPHAN)
GO
CREATE UNIQUE INDEX IDBAITEST
ON dbo.BAITEST (IDTEST)
GO
CREATE UNIQUE INDEX IDTRACNGHIEM
ON dbo.TRACNGHIEM (IDTRACNGHIEM)